import React from 'react';

export const AboutView: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-4xl font-bold text-gray-900 dark:text-gray-100 mb-6">About AI Detector</h1>
      
      <div className="prose prose-lg dark:prose-invert">
        <p className="text-xl text-gray-600 dark:text-gray-300 mb-6">
          The AI Detector was created to help people determine whether the content they're reading was written by a human or generated by artificial intelligence. As AI-generated content becomes increasingly prevalent, it's important to have tools that can help identify its source.
        </p>

        <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-200 mt-8 mb-4">How It Works</h2>
        <p className="text-gray-600 dark:text-gray-300 mb-6">
          Our tool analyzes various aspects of the text, including writing patterns, structural consistency, and natural language variations. It uses these indicators to estimate the likelihood that the content was generated by AI.
        </p>

        <div className="bg-blue-50 dark:bg-blue-900/30 border border-blue-100 dark:border-blue-800 rounded-lg p-6 mb-8">
          <h3 className="text-lg font-semibold text-blue-900 dark:text-blue-200 mb-2">Important Note</h3>
          <p className="text-blue-800 dark:text-blue-300">
            While our AI detection tool is sophisticated, it's not 100% accurate. The tool should be used as one of many factors in determining content authenticity, not as a definitive answer. Some human-written content may display AI-like patterns, and some AI-generated content may appear human-like.
          </p>
        </div>

        <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-4">Features</h2>
        <ul className="list-disc list-inside text-gray-600 dark:text-gray-300 mb-6">
          <li className="mb-2">Analysis of text structure and patterns</li>
          <li className="mb-2">Detailed breakdown of AI probability indicators</li>
          <li className="mb-2">Support for both direct text input and URL analysis</li>
          <li className="mb-2">Clear visualization of analysis results</li>
        </ul>
      </div>
    </div>
  );
};